version: "3.5"


networks:
  
  min_net:
    driver: bridge
    name: min_net


services:

  min-webrtc:
    image: local/min-webrtc
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: min-webrtc
    network_mode: host

